<?php

use Faker\Generator as Faker;

use App\Models\Address;

$states = [
    'Alabama',
    'Alaska',
    // 'American Samoa',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    // 'District of Columbia',
    'Florida',
    'Georgia',
    // 'Guam',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    // 'Puerto Rico',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    // 'Virgin Islands',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
];

$factory->define(Address::class, function (Faker $faker) use ($states) {
    return [
        'user_id' => 1,
        'first_name' => $faker->firstName,
        'last_name' => $faker->lastName,
        'street_address' => $faker->streetAddress,
        'extra_address' => $faker->streetSuffix,
        'postcode' => $faker->postcode,
        'city' => $faker->city,
        'state' => $states[array_rand($states)],
        'telephone' => $faker->phoneNumber
    ];
});
